baseurl: https://www.christianvillanueva.com/
languageCode: en-us
defaultContentLanguage: en
isMultilingual: no
title: Christian Villanueva
theme: hugo-theme-sam
pygmentsStyle: monokai
pygmentsCodefences: yes
params:
  dateform: Mon Jan 02, 2006
  dateformfull: Mon Jan 2 2006 15:04:05 EST
  description: A new Hugo site.
  favicon: sam.ico
  footerText: Powered by RedBull.
  homepage: main
  images: tn.png
  mainMenu:
    - link: post
      text: posts
    - link: gallery
      text: gallery
    - link: portfolio
      text: portfolio
    - link: about
      text: Christian? Tell me more
  title: Christian
  videoBackground:
    overlay: rgba(0, 0, 0, 0.4)
    sources:
      - poster: /background.png
        source: /sample_video.mp4
        type: video/mp4
imaging:
  quality: 75
